<?php
return array (
  'jpg' => 
  array (
    'id' => '1',
    'name' => 'COS',
    'host' => 'testbucket-1255602627.cos.ap-shanghai.myqcloud.com',
    'area' => 'sh',
    'appid' => '1255602627',
    'username' => 'AKIDsrgNwNBr9JH4f56wUFwTqMwRlw1As3qS',
    'password' => 'kiKsJpFzj2HVeXz5o6Ok2FSZWNFF8ISU',
    'port' => '21',
    'type' => 'cos',
    'bucket' => 'testbucket',
    'pasv' => '0',
    'ssl' => '0',
    'path' => '/',
    'url' => 'http://localhost:90/phpcms/uploadfile/',
    'stored' => '1',
  ),
  'jpeg' => 
  array (
    'id' => '1',
    'name' => 'COS',
    'host' => 'testbucket-1255602627.cos.ap-shanghai.myqcloud.com',
    'area' => 'sh',
    'appid' => '1255602627',
    'username' => 'AKIDsrgNwNBr9JH4f56wUFwTqMwRlw1As3qS',
    'password' => 'kiKsJpFzj2HVeXz5o6Ok2FSZWNFF8ISU',
    'port' => '21',
    'type' => 'cos',
    'bucket' => 'testbucket',
    'pasv' => '0',
    'ssl' => '0',
    'path' => '/',
    'url' => 'http://localhost:90/phpcms/uploadfile/',
    'stored' => '1',
  ),
  'gif' => 
  array (
    'id' => '1',
    'name' => 'COS',
    'host' => 'testbucket-1255602627.cos.ap-shanghai.myqcloud.com',
    'area' => 'sh',
    'appid' => '1255602627',
    'username' => 'AKIDsrgNwNBr9JH4f56wUFwTqMwRlw1As3qS',
    'password' => 'kiKsJpFzj2HVeXz5o6Ok2FSZWNFF8ISU',
    'port' => '21',
    'type' => 'cos',
    'bucket' => 'testbucket',
    'pasv' => '0',
    'ssl' => '0',
    'path' => '/',
    'url' => 'http://localhost:90/phpcms/uploadfile/',
    'stored' => '1',
  ),
  'bmp' => 
  array (
    'id' => '1',
    'name' => 'COS',
    'host' => 'testbucket-1255602627.cos.ap-shanghai.myqcloud.com',
    'area' => 'sh',
    'appid' => '1255602627',
    'username' => 'AKIDsrgNwNBr9JH4f56wUFwTqMwRlw1As3qS',
    'password' => 'kiKsJpFzj2HVeXz5o6Ok2FSZWNFF8ISU',
    'port' => '21',
    'type' => 'cos',
    'bucket' => 'testbucket',
    'pasv' => '0',
    'ssl' => '0',
    'path' => '/',
    'url' => 'http://localhost:90/phpcms/uploadfile/',
    'stored' => '1',
  ),
  'zip' => 
  array (
    'id' => '1',
    'name' => 'COS',
    'host' => 'testbucket-1255602627.cos.ap-shanghai.myqcloud.com',
    'area' => 'sh',
    'appid' => '1255602627',
    'username' => 'AKIDsrgNwNBr9JH4f56wUFwTqMwRlw1As3qS',
    'password' => 'kiKsJpFzj2HVeXz5o6Ok2FSZWNFF8ISU',
    'port' => '21',
    'type' => 'cos',
    'bucket' => 'testbucket',
    'pasv' => '0',
    'ssl' => '0',
    'path' => '/',
    'url' => 'http://localhost:90/phpcms/uploadfile/',
    'stored' => '1',
  ),
  'rar' => 
  array (
    'id' => '1',
    'name' => 'COS',
    'host' => 'testbucket-1255602627.cos.ap-shanghai.myqcloud.com',
    'area' => 'sh',
    'appid' => '1255602627',
    'username' => 'AKIDsrgNwNBr9JH4f56wUFwTqMwRlw1As3qS',
    'password' => 'kiKsJpFzj2HVeXz5o6Ok2FSZWNFF8ISU',
    'port' => '21',
    'type' => 'cos',
    'bucket' => 'testbucket',
    'pasv' => '0',
    'ssl' => '0',
    'path' => '/',
    'url' => 'http://localhost:90/phpcms/uploadfile/',
    'stored' => '1',
  ),
);
?>